### ISSUE TITLE
Client-side error: "t.searching.map is not a function" on self-hosted Vane (Windows + Docker)

### ISSUE THREAD

**Issue by themaxium-dot** [ItzCrazyKns/Perplexica#1075]
## Description

When I self-host Vane with Docker on Windows and run a web search, I frequently get this error in the browser:

> Application error: a client-side exception has occurred while loading localhost (see the browser console for more information).

The browser console always shows:

```text
2415-19b4fa5968a788ca.js:25 Uncaught TypeError: t.searching.map is not a function
    at 2415-19b4fa5968a788ca.js:25:17315
    at Array.map (<anonymous>)
    at es (2415-19b4fa5968a788ca.js:25:14918)
    at ak (4bd1b696-6b5c0c72b0eadc5f.js:1:53104)
    at o0 (4bd1b696-6b5c0c72b0eadc5f.js:1:73556)
    at is (4bd1b696-6b5c0c72b0eadc5f.js:1:84988)
    at sp (4bd1b696-6b5c0c72b0eadc5f.js:1:128009)
    at 4bd1b696-6b5c0c72b0eadc5f.js:1:127854
    at sd (4bd1b696-6b5c0c72b0eadc5f.js:1:127862)
    at sn (4bd1b696-6b5c0c72b0eadc5f.js:1:123787)

It looks like searching / queries is sometimes not an array, but the code assumes it is and calls .map() on it.

Environment
Vane version: itzcrazykns1337/vane:latest (pulled on 2026‑03‑21)

Deployment: Docker on Windows 11 (Docker Desktop, default settings)

Container name: vane

Ports:

3000:3000 (Vane)

Browser: Chrome / Edge (same behaviour)

SearXNG: bundled with the vane:latest image, working fine on its own

SearXNG + Brave Search API are working correctly:

I configured braveapi in /etc/searxng/settings.yml with my Brave Web Search API key.

Testing directly in SearXNG UI with KF-21 returns results.

Brave dashboard shows the API usage increasing as expected.

So the backend search pipeline is healthy; the error seems to be only in Vane’s query orchestration / UI layer.

Steps to Reproduce
Run Vane with Docker:

bash
docker run -d \
  -p 3000:3000 \
  -v vane-data:/home/vane/data \
  --name vane \
  itzcrazykns1337/vane:latest
Open http://localhost:3000 in the browser.

Complete the initial setup (LLM, etc.).

In the main UI, ask something like:

Search the latest information about KF-21

After a short time, the page shows:

Application error: a client-side exception has occurred while loading localhost

Open the browser dev tools → Console, and the t.searching.map is not a function error appears (stack trace above).

The error also appears in the container logs (docker logs vane --tail 100) as a.queries.map is not a function.

Expected Behavior
Vane should handle the search request without throwing a client-side exception.

Even if searching / queries is not an array (or is undefined), the code should guard against this and fail gracefully (or normalise the structure) instead of crashing the whole page.

Additional Notes
The error seems more frequent when using “research / discover‑style” queries that get broken into multiple sub‑queries.

With simpler one‑shot queries, the error happens less often, but I can still reproduce it.

Since SearXNG + Brave work fine in isolation, this looks like a bug in the Vane search pipeline, not in the search backend configuration.

If you need any additional logs or are interested in a specific debug build, I’m happy to test it on my setup.
